version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pixel-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_strong_password123!", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - pixel-network

  spacesservice:
    container_name: pixel-spaces
    build:
      context: ../src/SpacesService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8081
      - ConnectionStrings__Default=${SPACES_CONN}
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8081:8081"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - pixel-network

  bookingservice:
    container_name: pixel-bookings
    build:
      context: ../src/BookingService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8082
      - ConnectionStrings__Default=${BOOKINGS_CONN}
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8082:8082"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - pixel-network

networks:
  pixel-network:
    driver: bridge
